import type { SalesData } from './types';

const salesData: SalesData[] = [
  {
    "timestamp_incoming_webhook": "12/08/2025 12:48:55",
    "data_product_support_email": "",
    "data_product_has_co_production": "",
    "data_product_name": "TEMPLATE - 75 SOFT FEM",
    "data_product_warranty_date": "2025-08-19T00:00:00Z",
    "data_product_is_physical_product": "",
    "data_product_id": "5941532",
    "data_product_ucode": "289ed5d7-085a-4897-99c6-737bc2b3e91b",
    "data_product_content_has_physical_products": "",
    "data_product_content_products_0_name": "",
    "data_product_content_products_0_is_physical_product": "",
    "data_product_content_products_0_id": "",
    "data_product_content_products_0_ucode": "",
    "data_product_content_products_1_name": "",
    "data_product_content_products_1_is_physical_product": "",
    "data_product_content_products_1_id": "",
    "data_product_content_products_1_ucode": "",
    "data_commissions_0_currency_value": "BRL",
    "data_commissions_0_source": "MARKETPLACE",
    "data_commissions_0_value": "3,96",
    "data_commissions_1_currency_value": "BRL",
    "data_commissions_1_source": "PRODUCER",
    "data_commissions_1_value": "25,94",
    "data_purchase_original_offer_price_currency_value": "BRL",
    "data_purchase_original_offer_price_value": "29.90",
    "data_purchase_checkout_country_iso": "BR",
    "data_purchase_checkout_country_name": "Brasil",
    "data_purchase_sckPaymentLink": "",
    "data_purchase_order_bump_parent_purchase_transaction": "",
    "data_purchase_order_bump_is_order_bump": "",
    "data_purchase_approved_date": "1755013720000",
    "data_purchase_offer_code": "k6qwjvqe",
    "data_purchase_offer_coupon_code": "",
    "data_purchase_is_funnel": "",
    "data_purchase_event_tickets_amount": "",
    "data_purchase_order_date": "1755013660000",
    "data_purchase_price_currency_value": "BRL",
    "data_purchase_price_value": "29,9",
    "data_purchase_payment_installments_number": "1",
    "data_purchase_payment_type": "PIX",
    "data_purchase_full_price_currency_value": "BRL",
    "data_purchase_full_price_value": "29.90",
    "data_purchase_business_model": "I",
    "data_purchase_transaction": "HP0876639024",
    "data_purchase_status": "COMPLETED",
    "data_affiliates_0_affiliate_code": "",
    "data_affiliates_0_name": "",
    "data_producer_legal_nature": "Pessoa Jurídica",
    "data_producer_document": "55378532000159",
    "data_producer_name": "CAMILA FARO COMUNICACOES LTDA",
    "data_subscription_subscriber_code": "",
    "data_subscription_plan_name": "",
    "data_subscription_plan_id": "",
    "data_subscription_status": "",
    "data_buyer_checkout_phone_code": "11",
    "data_buyer_address_zipcode": "12953026",
    "data_buyer_address_country": "Brasil",
    "data_buyer_address_number": "218",
    "data_buyer_address_address": "Rua Miguel Cervantes",
    "data_buyer_address_city": "Atibaia",
    "data_buyer_address_state": "SP",
    "data_buyer_address_neighborhood": "Condomínio Atibaia Park I",
    "data_buyer_address_complement": "J18",
    "data_buyer_address_country_iso": "BR",
    "data_buyer_document": "44482480894",
    "data_buyer_name": "Vitória Marques",
    "data_buyer_last_name": "Marques",
    "data_buyer_checkout_phone": "11968601612",
    "data_buyer_first_name": "Vitória",
    "data_buyer_email": "vitoriamarquescampos@hotmail.com",
    "data_buyer_document_type": "CPF",
    "id": "e60bcae3-2b1f-4a55-8b49-2a6f65d4774e",
    "creation_date": "1755013730611",
    "event": "PURCHASE_APPROVED",
    "version": "2.0.0"
  },
  {
    "timestamp_incoming_webhook": "12/08/2025 13:02:29",
    "data_product_support_email": "",
    "data_product_has_co_production": "",
    "data_product_name": "Notion Template - Minha vida dos sonhos",
    "data_product_warranty_date": "2025-08-19T00:00:00Z",
    "data_product_is_physical_product": "",
    "data_product_id": "6004600",
    "data_product_ucode": "6af50132-bde5-4f3e-9c9d-4bb70141e8c2",
    "data_product_content_has_physical_products": "",
    "data_product_content_products_0_name": "",
    "data_product_content_products_0_is_physical_product": "",
    "data_product_content_products_0_id": "",
    "data_product_content_products_0_ucode": "",
    "data_product_content_products_1_name": "",
    "data_product_content_products_1_is_physical_product": "",
    "data_product_content_products_1_id": "",
    "data_product_content_products_1_ucode": "",
    "data_commissions_0_currency_value": "BRL",
    "data_commissions_0_source": "MARKETPLACE",
    "data_commissions_0_value": "3,96",
    "data_commissions_1_currency_value": "BRL",
    "data_commissions_1_source": "PRODUCER",
    "data_commissions_1_value": "23,45",
    "data_purchase_original_offer_price_currency_value": "BRL",
    "data_purchase_original_offer_price_value": "29.90",
    "data_purchase_checkout_country_iso": "BR",
    "data_purchase_checkout_country_name": "Brasil",
    "data_purchase_sckPaymentLink": "",
    "data_purchase_order_bump_parent_purchase_transaction": "",
    "data_purchase_order_bump_is_order_bump": "",
    "data_purchase_approved_date": "1755014533000",
    "data_purchase_offer_code": "0pxo3iu1",
    "data_purchase_offer_coupon_code": "",
    "data_purchase_is_funnel": "",
    "data_purchase_event_tickets_amount": "",
    "data_purchase_order_date": "1755014491000",
    "data_purchase_price_currency_value": "BRL",
    "data_purchase_price_value": "29,9",
    "data_purchase_payment_installments_number": "1",
    "data_purchase_payment_type": "PIX",
    "data_purchase_full_price_currency_value": "BRL",
    "data_purchase_full_price_value": "29.90",
    "data_purchase_business_model": "I",
    "data_purchase_transaction": "HP0593094409",
    "data_purchase_status": "COMPLETED",
    "data_affiliates_0_affiliate_code": "",
    "data_affiliates_0_name": "",
    "data_producer_legal_nature": "Pessoa Jurídica",
    "data_producer_document": "55378532000159",
    "data_producer_name": "CAMILA FARO COMUNICACOES LTDA",
    "data_subscription_subscriber_code": "",
    "data_subscription_plan_name": "",
    "data_subscription_plan_id": "",
    "data_subscription_status": "",
    "data_buyer_checkout_phone_code": "11",
    "data_buyer_address_zipcode": "12953026",
    "data_buyer_address_country": "Brasil",
    "data_buyer_address_number": "218",
    "data_buyer_address_address": "Rua Miguel Cervantes",
    "data_buyer_address_city": "Atibaia",
    "data_buyer_address_state": "SP",
    "data_buyer_address_neighborhood": "Condomínio Atibaia Park I",
    "data_buyer_address_complement": "J18",
    "data_buyer_address_country_iso": "BR",
    "data_buyer_document": "44482480894",
    "data_buyer_name": "Vitória Marques",
    "data_buyer_last_name": "Marques",
    "data_buyer_checkout_phone": "11968601612",
    "data_buyer_first_name": "Vitória",
    "data_buyer_email": "vitoriamarquescampos@hotmail.com",
    "data_buyer_document_type": "CPF",
    "id": "2e0de7bd-869e-4702-a078-a0119b53a8aa",
    "creation_date": "1755014543361",
    "event": "PURCHASE_APPROVED",
    "version": "2.0.0"
  },
  {
    "timestamp_incoming_webhook": "12/08/2025 17:47:39",
    "data_product_support_email": "",
    "data_product_has_co_production": "",
    "data_product_name": "ELA - Guia para a sua versão feminina.",
    "data_product_warranty_date": "2025-08-19T00:00:00Z",
    "data_product_is_physical_product": "",
    "data_product_id": "5468098",
    "data_product_ucode": "a0d09750-5ce5-46f0-938d-71369f88e782",
    "data_product_content_has_physical_products": "",
    "data_product_content_products_0_name": "",
    "data_product_content_products_0_is_physical_product": "",
    "data_product_content_products_0_id": "",
    "data_product_content_products_0_ucode": "",
    "data_product_content_products_1_name": "",
    "data_product_content_products_1_is_physical_product": "",
    "data_product_content_products_1_id": "",
    "data_product_content_products_1_ucode": "",
    "data_commissions_0_currency_value": "BRL",
    "data_commissions_0_source": "MARKETPLACE",
    "data_commissions_0_value": "30,4",
    "data_commissions_1_currency_value": "BRL",
    "data_commissions_1_source": "PRODUCER",
    "data_commissions_1_value": "264,11",
    "data_purchase_original_offer_price_currency_value": "BRL",
    "data_purchase_original_offer_price_value": "297",
    "data_purchase_checkout_country_iso": "BR",
    "data_purchase_checkout_country_name": "Brasil",
    "data_purchase_sckPaymentLink": "",
    "data_purchase_order_bump_parent_purchase_transaction": "",
    "data_purchase_order_bump_is_order_bump": "",
    "data_purchase_approved_date": "1755031642000",
    "data_purchase_offer_code": "bhzxyq3a",
    "data_purchase_offer_coupon_code": "",
    "data_purchase_is_funnel": "",
    "data_purchase_event_tickets_amount": "",
    "data_purchase_order_date": "1755031639000",
    "data_purchase_price_currency_value": "BRL",
    "data_purchase_price_value": "297",
    "data_purchase_payment_installments_number": "12",
    "data_purchase_payment_type": "CREDIT_CARD",
    "data_purchase_full_price_currency_value": "BRL",
    "data_purchase_full_price_value": "368.64",
    "data_purchase_business_model": "I",
    "data_purchase_transaction": "HP0756890171",
    "data_purchase_status": "COMPLETED",
    "data_affiliates_0_affiliate_code": "",
    "data_affiliates_0_name": "",
    "data_producer_legal_nature": "Pessoa Jurídica",
    "data_producer_document": "55378532000159",
    "data_producer_name": "CAMILA FARO COMUNICACOES LTDA",
    "data_subscription_subscriber_code": "",
    "data_subscription_plan_name": "",
    "data_subscription_plan_id": "",
    "data_subscription_status": "",
    "data_buyer_checkout_phone_code": "75",
    "data_buyer_address_zipcode": "44007-204",
    "data_buyer_address_country": "Brasil",
    "data_buyer_address_number": "30",
    "data_buyer_address_address": "Rua Vanderlei Carvalho",
    "data_buyer_address_city": "Feira de Santana",
    "data_buyer_address_state": "BA",
    "data_buyer_address_neighborhood": "Vila Olimpia ",
    "data_buyer_address_complement": "Casa L11",
    "data_buyer_address_country_iso": "BR",
    "data_buyer_document": "8879187511",
    "data_buyer_name": "Lyse de Melo",
    "data_buyer_last_name": "Melo",
    "data_buyer_checkout_phone": "75992227972",
    "data_buyer_first_name": "Lyse",
    "data_buyer_email": "lysegaby@hotmail.com",
    "data_buyer_document_type": "CPF",
    "id": "1a74d9c9-1fd5-409e-b7b8-3e5dd570a130",
    "creation_date": "1755031654041",
    "event": "PURCHASE_APPROVED",
    "version": "2.0.0"
  }
];

export { salesData };

    