import type { SalesData } from './types';
import { format } from 'date-fns';

const generateRandomDate = (start: Date, end: Date): string => {
  const date = new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
  return format(date, 'dd/MM/yyyy HH:mm:ss');
};

const startDate = new Date();
startDate.setDate(startDate.getDate() - 89);
const endDate = new Date();

const baseSample: Omit<SalesData, 'id' | 'timestamp_incoming_webhook' | 'data_purchase_approved_date' | 'data_purchase_price_value' | 'data_product_name' | 'data_purchase_payment_type' | 'data_buyer_address_state' | 'data_buyer_address_city' | 'data_purchase_transaction' | 'data_buyer_name' | 'data_buyer_email'> = {
  data_product_support_email: '',
  data_product_has_co_production: '',
  data_product_warranty_date: '2025-08-11T00:00:00Z',
  data_product_is_physical_product: '',
  data_product_id: '5468098',
  data_product_ucode: 'a0d09750-5ce5-46f0-938d-71369f88e782',
  data_product_content_has_physical_products: '',
  data_product_content_products_0_name: '',
  data_product_content_products_0_is_physical_product: '',
  data_product_content_products_0_id: '',
  data_product_content_products_0_ucode: '',
  data_product_content_products_1_name: '',
  data_product_content_products_1_is_physical_product: '',
  data_product_content_products_1_id: '',
  data_product_content_products_1_ucode: '',
  data_commissions_0_currency_value: 'BRL',
  data_commissions_0_source: 'MARKETPLACE',
  data_commissions_0_value: '30,4',
  data_commissions_1_currency_value: 'BRL',
  data_commissions_1_source: 'PRODUCER',
  data_commissions_1_value: '264,11',
  data_purchase_original_offer_price_currency_value: 'BRL',
  data_purchase_original_offer_price_value: '297',
  data_purchase_checkout_country_iso: 'BR',
  data_purchase_checkout_country_name: 'Brasil',
  data_purchase_sckPaymentLink: '',
  data_purchase_order_bump_parent_purchase_transaction: '',
  data_purchase_order_bump_is_order_bump: '',
  data_purchase_offer_code: 'bhzxyq3a',
  data_purchase_offer_coupon_code: '',
  data_purchase_is_funnel: '',
  data_purchase_event_tickets_amount: '',
  data_purchase_order_date: '1754346702000',
  data_purchase_price_currency_value: 'BRL',
  data_purchase_payment_installments_number: '1',
  data_purchase_full_price_currency_value: 'BRL',
  data_purchase_full_price_value: '297',
  data_purchase_business_model: 'I',
  data_purchase_status: 'COMPLETED',
  data_affiliates_0_affiliate_code: '',
  data_affiliates_0_name: '',
  data_producer_legal_nature: 'Pessoa Jurídica',
  data_producer_document: '55378532000159',
  data_producer_name: 'CAMILA FARO COMUNICACOES LTDA',
  data_subscription_subscriber_code: '',
  data_subscription_plan_name: '',
  data_subscription_plan_id: '',
  data_subscription_status: '',
  data_buyer_checkout_phone_code: '27',
  data_buyer_address_zipcode: '29101022',
  data_buyer_address_country: 'Brasil',
  data_buyer_address_number: '2124',
  data_buyer_address_address: 'Avenida Antônio Gil Veloso',
  data_buyer_address_neighborhood: 'Praia da Costa',
  data_buyer_address_complement: 'Apto. 202',
  data_buyer_address_country_iso: 'BR',
  data_buyer_document: '13975467789',
  data_buyer_last_name: 'Carvalho',
  data_buyer_checkout_phone: '27992686615',
  data_buyer_first_name: 'Amanda',
  data_buyer_document_type: 'CPF',
  creation_date: '1755000069279',
  event: 'PURCHASE_APPROVED',
  version: '2.0.0',
};

const sampleSales: SalesData[] = [
  {
    ...baseSample,
    id: 'e895cf03-e11d-42cf-9024-d777b15c1000',
    timestamp_incoming_webhook: generateRandomDate(startDate, endDate),
    data_purchase_approved_date: String(new Date().getTime()),
    data_purchase_price_value: '297.00',
    data_purchase_full_price_value: '297.00',
    data_purchase_original_offer_price_value: '297.00',
    data_product_name: 'ELA - Guia para a sua versão feminina.',
    data_purchase_payment_type: 'CREDIT_CARD',
    data_buyer_address_state: 'SP',
    data_buyer_address_city: 'São Paulo',
    data_purchase_transaction: 'HP3742016800',
    data_buyer_name: 'Mariana Silva',
    data_buyer_first_name: 'Mariana',
    data_buyer_last_name: 'Silva',
    data_buyer_email: 'mariana.silva@example.com',
  },
  {
    ...baseSample,
    id: 'e895cf03-e11d-42cf-9024-d777b15c1001',
    timestamp_incoming_webhook: generateRandomDate(startDate, endDate),
    data_purchase_approved_date: String(new Date().getTime()),
    data_purchase_price_value: '497.00',
    data_purchase_full_price_value: '497.00',
    data_purchase_original_offer_price_value: '497.00',
    data_product_name: 'ELA - Guia para a sua versão feminina.',
    data_purchase_payment_type: 'PIX',
    data_buyer_address_state: 'RJ',
    data_buyer_address_city: 'Rio de Janeiro',
    data_purchase_transaction: 'HP3742016801',
    data_buyer_name: 'Lucas Santos',
    data_buyer_first_name: 'Lucas',
    data_buyer_last_name: 'Santos',
    data_buyer_email: 'lucas.santos@example.com',
  },
  {
    ...baseSample,
    id: 'e895cf03-e11d-42cf-9024-d777b15c1002',
    timestamp_incoming_webhook: generateRandomDate(startDate, endDate),
    data_purchase_approved_date: String(new Date().getTime()),
    data_purchase_price_value: '297.00',
    data_purchase_full_price_value: '297.00',
    data_purchase_original_offer_price_value: '297.00',
    data_product_name: 'ELA - Guia para a sua versão feminina.',
    data_purchase_payment_type: 'BILLET',
    data_buyer_address_state: 'MG',
    data_buyer_address_city: 'Belo Horizonte',
    data_purchase_transaction: 'HP3742016802',
    data_buyer_name: 'Beatriz Oliveira',
    data_buyer_first_name: 'Beatriz',
    data_buyer_last_name: 'Oliveira',
    data_buyer_email: 'beatriz.oliveira@example.com',
  }
];

export const salesData: SalesData[] = sampleSales;
