export type SalesData = {
  timestamp_incoming_webhook: string;
  data_product_support_email: string;
  data_product_has_co_production: string;
  data_product_name: string;
  data_product_warranty_date: string;
  data_product_is_physical_product: string;
  data_product_id: string;
  data_product_ucode: string;
  data_product_content_has_physical_products: string;
  data_product_content_products_0_name: string;
  data_product_content_products_0_is_physical_product: string;
  data_product_content_products_0_id: string;
  data_product_content_products_0_ucode: string;
  data_product_content_products_1_name: string;
  data_product_content_products_1_is_physical_product: string;
  data_product_content_products_1_id: string;
  data_product_content_products_1_ucode: string;
  data_commissions_0_currency_value: string;
  data_commissions_0_source: string;
  data_commissions_0_value: string;
  data_commissions_1_currency_value: string;
  data_commissions_1_source: string;
  data_commissions_1_value: string;
  data_purchase_original_offer_price_currency_value: string;
  data_purchase_original_offer_price_value: string;
  data_purchase_checkout_country_iso: string;
  data_purchase_checkout_country_name: string;
  data_purchase_sckPaymentLink: string;
  data_purchase_order_bump_parent_purchase_transaction: string;
  data_purchase_order_bump_is_order_bump: string;
  data_purchase_approved_date: string;
  data_purchase_offer_code: string;
  data_purchase_offer_coupon_code: string;
  data_purchase_is_funnel: string;
  data_purchase_event_tickets_amount: string;
  data_purchase_order_date: string;
  data_purchase_price_currency_value: string;
  data_purchase_price_value: string;
  data_purchase_payment_installments_number: string;
  data_purchase_payment_type: 'PIX' | 'CREDIT_CARD' | 'BILLET' | 'PAYPAL';
  data_purchase_full_price_currency_value: string;
  data_purchase_full_price_value: string;
  data_purchase_business_model: string;
  data_purchase_transaction: string;
  data_purchase_status: 'COMPLETED' | 'CANCELLED' | 'REFUNDED' | 'DISPUTE' | 'BLOCKED' | 'PARTIAL_REFUNDED' | 'BILLET_PRINTED' | 'WAITING_PAYMENT';
  data_affiliates_0_affiliate_code: string;
  data_affiliates_0_name: string;
  data_producer_legal_nature: string;
  data_producer_document: string;
  data_producer_name: string;
  data_subscription_subscriber_code: string;
  data_subscription_plan_name: string;
  data_subscription_plan_id: string;
  data_subscription_status: string;
  data_buyer_checkout_phone_code: string;
  data_buyer_address_zipcode: string;
  data_buyer_address_country: string;
  data_buyer_address_number: string;
  data_buyer_address_address: string;
  data_buyer_address_city: string;
  data_buyer_address_state: string;
  data_buyer_address_neighborhood: string;
  data_buyer_address_complement: string;
  data_buyer_address_country_iso: string;
  data_buyer_document: string;
  data_buyer_name: string;
  data_buyer_last_name: string;
  data_buyer_checkout_phone: string;
  data_buyer_first_name: string;
  data_buyer_email: string;
  data_buyer_document_type: string;
  id: string;
  creation_date: string;
  event: string;
  version: string;
};

export type DateRange = {
  from: Date | undefined;
  to: Date | undefined;
};
